// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDycWVWnmZg8A2VCwgTAcZzb__rcyGW5oE',
    appId: '1:772406392874:web:7cb74354f01916819aab53',
    messagingSenderId: '772406392874',
    projectId: 'task-manager-155bf',
    authDomain: 'task-manager-155bf.firebaseapp.com',
    storageBucket: 'task-manager-155bf.appspot.com',
    measurementId: 'G-RE97XFZCQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcGd6BGauXJZK_rGcgwfvoY0j_2lfe81U',
    appId: '1:772406392874:android:516766df9b94f17e9aab53',
    messagingSenderId: '772406392874',
    projectId: 'task-manager-155bf',
    storageBucket: 'task-manager-155bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEjKLlUFYBGrY2BLA3QjbJ5MKYGUQA230',
    appId: '1:772406392874:ios:7deaa2fd996dd2f59aab53',
    messagingSenderId: '772406392874',
    projectId: 'task-manager-155bf',
    storageBucket: 'task-manager-155bf.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEjKLlUFYBGrY2BLA3QjbJ5MKYGUQA230',
    appId: '1:772406392874:ios:6574685284c5247c9aab53',
    messagingSenderId: '772406392874',
    projectId: 'task-manager-155bf',
    storageBucket: 'task-manager-155bf.appspot.com',
    iosBundleId: 'com.example.taskmanager.RunnerTests',
  );
}
